---
title: "Vincenzo Coia's CV"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
---

email: vincenzo.coia@gmail.com

## Work Experience

2017/01 - present    
**Postdoctoral Teaching and Learning Fellow**    
Masters of Data Science Program, the University of British Columbia    
Vancouver, BC    

2009/05 - 2014/05    
**Short-term statistical consulting** (6 projects)    
UBC and private    

## Education

**PhD in Statistics**    
2012/09 - 2017/02    
The University of British Columbia    
Conferred May 29, 2017    

**MSc in Mathematics and Statistics (Statistics)**    
2011/09 - 2012/08    
Brock University    
Conferred on October 13, 2012    

**BSc (3-year) in Biological Sciences**    
Minor in Earth Sciences    
2005/09 - 2011/04    
Brock University    
Conferred "With Distinction" on October 22, 2011    

**BSc (Honours) Mathematics Integrated with Computers and Applications**    
Concentration in Statistics    
2005/09 - 2011/04    
Brock University    
Conferred "With First-Class Standing" on June 7, 2011    

### Volunteer Positions

2016/09 - 2016/02    
**Science World at TELUS World of Science **    
Vancouver, BC    
78.15 hours    

2013/10 - 2014/05    
**Beaty Biodiversity Museum: Events Volunteer**    
Vancouver, BC    
35.0 hours    

2013/04 - 2013/09    
**UBC Farm**    
Vancouver, BC    
102.5 hours    

2011/06 - 2011/08    
**Project S.H.A.R.E. community garden**    
Niagara Falls, ON    
15.0 hours   


### Research Assistantships

2013/05 - 2013/08    
**Robust penalized regression**    
Supervisor: Dr. Gabriela Cohen-Freue    
Department of Statistics    
The University of British Columbia    
Vancouver, BC    

2012/05 - 2012/08    
2011/05 - 2011/08    
2010/05 - 2010/08    
**Extreme value modelling**    
Supervisor: Dr. Mei Ling Huang    
Department of Mathematics    
Brock University    
St. Catharines, ON    

2010/09 - 2011/06    
**Quantum monte carlo simulations**    
Supervisors: Dr. Stuart Rothstein; Dr. Wai Kong (John) Yuen    
Department of Chemistry and Department of Mathematics    
Brock University    
St. Catharines, ON    


### Teaching Assistantships

__Duration__: From the latter part of my undergrad, to the end of my PhD.

UBC:

- **SCIE 300: Communicating Science** (5x)    

Brock University:

- **MATH 4P82/5P82: Non-parametric Statistics**
- **MATH 3P82: Regression Analysis**
- **MATH 4P81/5P81: Sampling Theory**
- **MATH 3P81: Experimental Design** (2x)
- **MATH 2F40: Mathematics Integrated w/ Computers and Applications II**


## Publications and Talks

### Articles Submitted to Refereed Journals

-   Huang, M.L., Coia, V., and Brill, P.H. (2013) A cluster truncated
    Pareto distribution and its applications. ISRN Probability and
    Statistics 2013: Article ID 265373.

-   Ayad, M., Coia, V., and Kihel, O. (2014) The number of relatively
    prime subsets of a finite union of sets of consecutive integers.
    Journal of Integer Sequences 17: Article 14.3.7

-   Coia, V., and Huang, M.L. (2014) A sieve model for extreme
    values. Journal of Statistical Computation and Simulation.
    84(8):16921710.

### Articles Submitted to Conference Proceedings

-   Huang, M. L., Coia, V., and Brill, P.H., A mixture truncated
    Pareto distribution, In JSM Proceedings 2012, Statistical Computing
    Section, Alexandria, VA: American Statistical Association, pp.
    24882498.

### Conference and Roundtable Contributions

-   Coia, V., Nolde, N., and Joe, H. Forecasting Extremes for Flooding
    (Invited Talk). The 44th Annual Meeting of the Statistical Society
    of Canada. May 29June 1, 2016 at Brock University, St. Catharines,
    ON.

-   Coia, V., and Jeanniard du Dot, T. (Invited Demonstration) "Using
    the Grammar of Graphics and Interactivity to explore Biologging Data
    in R". May 6, 2015. Building a Bioanalytical Theory for Analysis of
    Marine Mammal Movements: A Peter Wall International Research
    Roundtable. The University of British Columbia, Vancouver, BC.

-   Coia, V. "Flood Warning: An Application of High-Quantile Regression"
    (Contributed Talk). SFU/UBC Joint Graduate Student Seminar (Winter).
    February 28, 2015 at the SFU Harbour Centre, Vancouver, BC.

-   Coia, V. "A New Sieve Model for Extreme Values" (Contributed Talk).
    SFU/UBC Joint Graduate Student Seminar (Fall). September 29, 2012 at
    the SFU Harbour Centre, Vancouver, BC.

-   Coia, V., and Huang, M.L. "On Estimation of Heavy Tailed
    Distributions" (Contributed Talk). The 40th Annual Meeting of the
    Statistical Society of Canada. June 36, 2012 at the University of
    Guelph, Guelph, ON.

-   Huang, M.L., Coia, V., and Brill, P.H. "A Mixture Truncated Pareto
    Distribution" (Contributed Talk). The 2012 Joint Statistical
    Meetings. July 28August 2, 2012 at San Diego, California


## Awards

### University Issued

- 2012/09 - 2016/08: Four-Year Fellowship
- 2012/09 - 2016/08: Faculty of Science Graduate Award
- 2011/09: Dean of Graduate Studies Excellence Scholarship
- 2011/06/07: Dean's Gold Medal
- 2011/06/07: Distinguished Undergraduate Student Award in Mathematics
- 2011/03: President's Surgite Award

### Nationally Recognized

- 2013/06: Governor General of Canada's Gold Medal
- 2012/09 - 2015/08: NSERC Postgraduate Award (Doctoral, 3-year)
- 2011/09 - 2012/08: NSERC Alexander Graham Bell Canada Graduate Scholarship (Masters)
- 2010/05 - 2010/08: NSERC Undergraduate Student Research Award

### Individual Donors

- 2012/04: Dr. Jack Lightstone & Dorothy Markiewicz Scholarship
- 2012/04: Dr. Raymond & Mrs. Sachi Moriyama Grad. Fellowship
- 2012/03: Tomlinson Entrance Scholarship for Excellence in Mathematics and Science
- 2011/06: John and Roslyn Reed Book Prize
- 2010/09: Art Bicknell Scholarship in Mathematics
- 2010/09: Ian D. Beddis Family Scholarship
- 2010/09: Terry and Sue White Mathematics and Science Scholarship
- 2007/09: M.J. ("Mel") Farquharson Scholarship
- 2006/09: Scholler Foundation Scholarship in Chemistry

### Athletic Awards

- 2016/04/03: Sportsmanship Award, UBC Thunderbirds Sport Clubs (Fencing)
- 2016/02/28: Bronze Medal in Senior Mixed Epee (Intercollegiate Tournament, UBC)
- 2015/11/16: Bronze Medal in Senior Mixed Epee (Remembrance Day Tournament, UBC)
- 2012/03/28: RM Davis Surgite Award
- 2009/12/12: First Place Award Winter Epeedemic, Toronto Fencing Club
- 2009/03: Varsity Fencing Rookie of the Year Award

### Declined Awards

- 2012/04: Ontario Graduate Scholarship (Doctoral)
- 2011/05: Ontario Graduate Scholarship (Masters)

## Professional Activities

Dept. of Statistics, The University of British Columbia:

- 2016/05 - 2016/06: **Search committee member (for CRC 2 faculty position)**
- 2015/04/30: **Organizer of the "[How to Write an Awesome Abstract](http://stat.ubc.ca/~vincen.coia/abstractworkshop.html)" workshop**
- 2014/06 - 2015/05: **Organizer of the [SFU/UBC Joint Seminar](http://stat.ubc.ca/~vincen.coia/seminar.html)**
- 2014/06 - 2014/09: **Organizer of the Graduate Student Trip**
- 2014/04 - 2015/05: **Co-founder of the Graduate Writing Forums**
- 2013/06 - 2014/05: **Statistics Graduate Student Representative**