---
title: "The Binomial Distribution"
output: html_document
---

[ ] __Materials__: Paper and pen/pencil.

## Pre-quiz

1. Suppose you have 6-sided and fair dice. What's the probability of rolling:
    1. A 3 on the roll of a die?
    2. Snake-eyes? (i.e., two 1's after rolling two dice).
2. On a given day, there's a 50% chance that your toaster works. What's the probability that...
    1. your toaster works exactly one day in a given week?
    2. BONUS: your toaster works at least one day in a given week?

[ ] Pre-quiz done!

## Share your answers

What did you all get?

How did you come up with those numbers?

These can all be calculated using the __Binomial distribution_!

Anyone familiar?

[ ] Sharing done!

## Learning Objectives

By the end of the lesson, when faced with the task of computing a probability, learners are anticipated to be able to:

- Identify whether the probability can be computed using the binomial distribution.
- Apply the binomial distribution formula to compute the probability.

[ ] Objectives done!

## 1\. Can the Binomial distribution be used to compute a probability?

You need two ingredients.

### Ingredient \#1:

_Outcome = number of "wins" of independent "games"._

__Question__: What are the "games" in the pre-quiz questions? What's a "win"?

- [ ] I'll do Q1
- [ ] Can you do Q2?

[ ] Ingredient 1 done!

### Ingredient \#2:

_The probability of winning a game stays the same across games._

[ ] __Question__: What are the probabilities of winning a game for Q1 and Q2? Are they the same across games?

[ ] Ingredient 2 done! All ingredients done!

## 2\. How to use the Binomial distribution to compute a probability

Formula for $x$ wins out of $n$ games. Probability of success $p$:

$$\frac{n!}{x!(n-x)!}p^x(1-p)^{n-x}$$

__Activity__:

1. [ ] Let's work through Q1 together
2. [ ] You do Q2 on your own. Write it down!
3. [ ] Share/revise answers with peer.
4. [ ] Communicate answers (answers below)

[ ] Using the formula = done!

## Summary

- Use the binomial distribution to compute probability of number of "wins".
- A "win" can be _so many things_!
    - rain (vs. not rain)
    - getting to work in less than 30 minutes (vs. not)
    - passing a course (vs. not)
    - etc...

## Answers

1. ...
    1. 1/6 = 0.1667
    2. 1/36 = 0.02778
2. ...
    1. 0.0546875
    2. (1 - prob of never works) = 1 - 0.0078125 = 0.9921875