---
title: "Improv and Life"
output: github_document
---

Who's seen improv shows? Knows lessons?

## Learning Objective

By the end of today's lesson, using two activities based on improv theatre, learners are anticipated to

- Demonstrate how saying yes to ideas opens up new possibilities in work and life. 

## Activity #1: Yes, and...; Yeah, but...

__Part 1:__

- Pair up. 
- Someone starts: "Hey! Let's [activity]!!"
- Go back and forth: "Yes! And, [...]".
- I'll stop you after 1 minute.
- Rule: you _must_ give an _overly_ enthusiastic "yes". 

__Part 2:__

Same thing, but say "yeah, but..."

- Rule: appear displeased with the others' suggestion.

__Discussion:__

- Any take-aways?
- When is either useful?
- Which type of person are you?

## Activity #2: Story time

Teams: one big team of 5.

Goal: Build a cohesive story in a team, using 5 parts.

Each person gets a component of the story:

- Setting
- characters
- problem
- stakes
- solution

__Discussion__:

- Any take-aways?

## Summary

Saying yes in group settings leads to new opportunities!

Use "yeah, but..." to refine ideas. 