---
title: "Varimax Rotation"
author: "Vincenzo Coia"
output: html_document
---


### What is Varimax?

In 1(b), you saw that there are many loadings matrices that we can take so that the Factor Analysis assumptions are still satisfied (i.e., more than one loadings matrix "works"). We explored some of the possible loadings matrices by multiplying by a rotation matrix, denoted $R$ in the lab assignment.

The _varimax rotation_ is one such rotation that leads to loadings vectors that have a desirable property (in terms of interpretation): it "polarizes" the loadings vectors so that the values within a vector are either close to zero or are large in magnitude. A nicely "polarized" loadings vector is useful for interpretation, because features that are relevant to the underlying factor become easier to identify. For example, if the loadings vector for Factor 1 has loadings close to 1 for Features A and B, and close to zero for all other features, then we can look for something common between Features A and B (for example, "bitter flavour") that describes the factor underlying the data.

How can one achieve a loadings matrix whose vectors are polarized as much as possible? We need some concrete measure of "polarity" to maximize. _One_ trick is to maximize the __variance__ of the _squared_ loadings (squaring the loadings allows us to disregard sign). This is what varimax does.

The specific formula can be found on Slide 29 in Lecture 6.  

### Your task

Write a function in R that takes a value of $\theta$, and does the following:

1. Computes the rotation matrix $R$.
2. Computes the rotated loadings $L_R = LR$.
3. Computes sum of variances of the squared loadings in each column of $L_R$. 

This function returns a measure of "polarity" in your loadings vectors (in terms of the total variance) -- the larger the total variance, the more polarized your loadings vectors are. As such, you should find the value of $\theta$ that maximizes this "polarity" (maximizes this function). Use this $\theta$ to compute your rotated loadings.